In [ ]:
## Importing libraries

!pip install librosa
!pip install tqdm
!pip install plotly
import os
import random
import sys
import glob
import IPython.display as ipd
import librosa
import librosa.display
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy.stats
import warnings
from sklearn.model_selection import StratifiedShuffleSplit
from scipy.fftpack import fft
from scipy import signal
from scipy.io import wavfile
from tqdm import tqdm
import plotly.offline as py

warnings.simplefilter("ignore")
pd.set_option('display.max_columns', None)
py.init_notebook_mode(connected=True)

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 28.8 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 1.25.2
    Uninstalling numpy-1.25.2:
      Successfully uninstalled numpy-1.25.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
chex 0.1.7 requires jax>=0.4.6, but you have jax 0.3.25 which is incompatible.
flax 0.7.0 requires jax>=0.4.2, but you have jax 0.3.25 which is incompatible.
orbax-checkpoint 0.3.1 requires jax>=0.4.9, but you have jax 0.3.25 which is incompatible.


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!cp '/content/drive/MyDrive/ravdess.zip' .
!unzip  -q ravdess.zip

In [ ]:
import os
import glob

def metadata(basepath):
    df = pd.DataFrame(columns=['path', 'source', 'actor', 'gender', 'intensity', 'statement', 'repetition', 'emotion'])
    count = 0

    actor_folders = glob.glob(basepath)
    for actor_folder in actor_folders:
     if os.path.isdir(actor_folder):
        try:
            actor = int(os.path.basename(actor_folder).split('_')[-1])
        except ValueError:
            print("Invalid actor folder:", actor_folder)
            continue

        actor_files = glob.glob(actor_folder + '/*.wav')
        for file_path in actor_files:
            print("Actor folder:", actor_folder)  # Print the actor_folder for troubleshooting
            actor = int(os.path.basename(actor_folder).split('_')[-1])  # Extract the actor number correctly
            filename = os.path.basename(file_path).split('.')[0].split('-')
            if len(filename) == 7:
                src = int(filename[1])
                emotion = int(filename[2])

                gender = "female" if actor % 2 == 0 else "male"
                intensity = 0 if filename[3] == '01' else 1
                statement = 0 if filename[4] == '01' else 1
                repeat = 0 if filename[5] == '01' else 1

                df.loc[count] = [file_path, src, actor, gender, intensity, statement, repeat, emotion]
                count += 1


    labels = []
    y = []
    for i in range(len(df)):
        if df.emotion.iloc[i] == 1:
            label = "_neutral"
            y.append(1)
        elif df.emotion.iloc[i] == 2:
            label = "_calm"
            y.append(2)
        elif df.emotion.iloc[i] == 3:
            label = "_happy"
            y.append(3)
        elif df.emotion.iloc[i] == 4:
            label = "_sad"
            y.append(4)
        elif df.emotion.iloc[i] == 5:
            label = "_angry"
            y.append(5)
        elif df.emotion.iloc[i] == 6:
            label = "_fearful"
            y.append(6)
        elif df.emotion.iloc[i] == 7:
            label = "_disgust"
            y.append(7)
        elif df.emotion.iloc[i] == 8:
            label = "_surprised"
            y.append(8)
        else:
            label = "_none"

        # Add gender to the label
        labels.append(label)

    df['label'] = labels

    return df

basepath = '/content/Actor_*'
df = metadata(basepath)


Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor fo

In [ ]:
y = df.emotion.values.tolist()

In [ ]:
!pip install colorednoise


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import random
import colorednoise as cn

class Spectrograms():
    def __init__(self, df, datasettype, outputpath, sample=False, augmentation=False, mel=True, mfcc=False, spectral=False, mfccbanks=20, n_mels=128):
        self.df = df
        self.augmentation = augmentation
        self.mel = mel
        self.mfcc = mfcc
        self.spectral = spectral
        self.mfccbanks = mfccbanks
        self.n_mels = n_mels
        self.outputpath = outputpath
        self.datasettype = datasettype
        self.sample = sample

    def get_spectrograms(self):
        if self.sample:
            x, sample_rate = librosa.load(self.df.index[0])
            self.generate(x, sample_rate, '', 0, snr=0)

        else:
            for file in tqdm(range(self.df.shape[0])):
                emotion = df.iloc[file, df.columns.get_loc('label')]
                path = self.outputpath+self.datasettype+"/"+str(emotion)+"/"

                if not os.path.isdir(path):
                    os.makedirs(path)

                ## Reading signal from .wav file
                x, sample_rate = librosa.load(self.df.index[file])
                emo = df.iloc[file, df.columns.get_loc('emotion')]
                self.generate(x, sample_rate, path, file, emo)


    def generate(self, x, sample_rate, path, count, emo, snr=0):
        if self.mel:
            mel_features = librosa.feature.melspectrogram(y=x, sr=sample_rate, n_mels=self.n_mels)

            log_mel_features = librosa.power_to_db(mel_features, ref=np.max)
            fig = plt.figure(figsize=(12,4))
            ax = plt.Axes(fig, [0., 0., 1., 1.])
            ax.set_axis_off()
            fig.add_axes(ax)
            librosa.display.specshow(log_mel_features, sr=sample_rate, x_axis='time', y_axis='mel')
            if self.sample:
                plt.show()
            else:
                plt.close()

            if snr is not None:
                # Calculate noise power based on desired SNR
                signal_power = np.mean(x**2)
                noise_power = signal_power / (10**(snr/10))

                # Generate pink noise with the calculated power
                noise = cn.powerlaw_psd_gaussian(1, len(x))
                scaled_noise = np.sqrt(noise_power) * noise
                x_with_noise = x + scaled_noise

                # Generate spectrogram for the noisy signal
                mel_features_with_noise = librosa.feature.melspectrogram(y=x_with_noise, sr=sample_rate, n_mels=self.n_mels)
                log_mel_features_with_noise = librosa.power_to_db(mel_features_with_noise, ref=np.max)

                # Display or save the spectrogram with noise
                fig_with_noise = plt.figure(figsize=(12,4))
                ax_with_noise = plt.Axes(fig_with_noise, [0., 0., 1., 1.])
                ax_with_noise.set_axis_off()
                fig_with_noise.add_axes(ax_with_noise)
                librosa.display.specshow(log_mel_features_with_noise, sr=sample_rate, x_axis='time', y_axis='mel')
                if self.sample:
                    plt.show()
                else:
                    plt.savefig(path+str(emo)+"-"+str(count)+"_with_noise.jpg")
                plt.close(fig_with_noise)

        if self.mfcc:
            mfcc_features = librosa.feature.mfcc(x, sr=sample_rate, n_mfcc=self.mfccbanks)
            fig = plt.figure(figsize=(12,4))
            ax = plt.Axes(fig, [0., 0., 1., 1.])
            ax.set_axis_off()
            fig.add_axes(ax)
            librosa.display.specshow(mfcc_features, sr=sample_rate, x_axis='time', y_axis='mel')
            if self.sample:
                plt.show()
            else:
                plt.savefig(path+"mfccspectrogram_"+str(count)+".jpg")
                plt.close()

        if self.spectral:
            spectral_features = librosa.feature.spectral_contrast(x, sr=sample_rate)
            fig = plt.figure(figsize=(12,4))
            ax = plt.Axes(fig, [0., 0., 1., 1.])
            ax.set_axis_off()
            fig.add_axes(ax)
            librosa.display.specshow(spectral_features, sr=sample_rate, x_axis='time', y_axis='mel')
            if self.sample:
                plt.show()
            else:
                plt.savefig(path+"spectralspectrogram_"+str(count)+".jpg")
                plt.close()


In [ ]:
df_new = metadata('/content/Actor_*')

Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor folder: /content/Actor_07
Actor fo

In [ ]:
df_new.index = df_new.path
df_new = df_new.drop("path", axis=1)

In [ ]:
spectrograms = Spectrograms(df_new, 'images_new', '/content/spectrograms', sample=False)
spectrograms.get_spectrograms()

100%|██████████| 1440/1440 [04:46<00:00,  5.02it/s]


In [ ]:
!pip install opencv-python
import os
import cv2
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
categories = os.listdir("/content/spectrogramsimages_new")
len(categories)

8

In [ ]:
def load_images_and_labels(categories):
    img_lst=[]
    labels=[]
    for index, category in enumerate(categories):
        for image_name in os.listdir(fpath+"/"+category):
            img = cv2.imread(fpath+"/"+category+"/"+image_name)
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

            img_array = Image.fromarray(img, 'RGB')

            #resize image to 224 x 224 because the input image resolution for GoogleNet is 224 x 224
            resized_img = img_array.resize((224, 224))

            img_lst.append(np.array(resized_img))

            labels.append(index)
    return img_lst, labels

fpath = "/content/spectrogramsimages_new"
images, labels = load_images_and_labels(categories)
print("No. of images loaded = ",len(images),"\nNo. of labels loaded = ",len(labels))
print(type(images),type(labels))


No. of images loaded =  1440 
No. of labels loaded =  1440
<class 'list'> <class 'list'>


In [ ]:
images = np.array(images)
labels = np.array(labels)

print("Images shape = ",images.shape,"\nLabels shape = ",labels.shape)
print(type(images),type(labels))

Images shape =  (1440, 224, 224, 3) 
Labels shape =  (1440,)
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [ ]:
#1-step in data shuffling
random_seed=42
#get equally spaced numbers in a given range
n = np.arange(images.shape[0])
print("'n' values before shuffling = ",n)

#shuffle all the equally spaced values in list 'n'
np.random.seed(random_seed)
np.random.shuffle(n)
print("\n'n' values after shuffling = ",n)

'n' values before shuffling =  [   0    1    2 ... 1437 1438 1439]

'n' values after shuffling =  [ 168  605  548 ... 1294  860 1126]


In [ ]:
#2-step in data shuffling

#shuffle images and corresponding labels data in both the lists
images = images[n]
labels = labels[n]

print("Images shape after shuffling = ",images.shape,"\nLabels shape after shuffling = ",labels.shape)

Images shape after shuffling =  (1440, 224, 224, 3) 
Labels shape after shuffling =  (1440,)


In [ ]:
images = images.astype(np.float32)
labels = labels.astype(np.int32)
images = images/255
print("Images shape after normalization = ",images.shape)

Images shape after normalization =  (1440, 224, 224, 3)


In [ ]:
x_train, x_test, y_train, y_test = train_test_split(images, labels, test_size = 0.2, random_state = random_seed)

print("x_train shape = ",x_train.shape)
print("y_train shape = ",y_train.shape)
print("\nx_test shape = ",x_test.shape)
print("y_test shape = ",y_test.shape)

x_train shape =  (1152, 224, 224, 3)
y_train shape =  (1152,)

x_test shape =  (288, 224, 224, 3)
y_test shape =  (288,)


In [ ]:
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Conv2D,MaxPooling2D,Dense,Flatten,Dropout
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Dense, Flatten, Dropout, BatchNormalization


In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dense, Dropout, Flatten, BatchNormalization, Concatenate, AveragePooling2D

def inception_module(x, filters):
    # 1x1 convolution
    conv1x1 = Conv2D(filters[0], (1, 1), padding='same', activation='relu')(x)

    # 3x3 convolution
    conv3x3 = Conv2D(filters[1], (3, 3), padding='same', activation='relu')(x)

    # 5x5 convolution
    conv5x5 = Conv2D(filters[2], (5, 5), padding='same', activation='relu')(x)

    # Max pooling
    max_pool = MaxPooling2D((3, 3), strides=(1, 1), padding='same')(x)
    max_pool_conv = Conv2D(filters[3], (1, 1), padding='same', activation='relu')(max_pool)

    # Concatenate the outputs of the different paths
    output = Concatenate()([conv1x1, conv3x3, conv5x5, max_pool_conv])
    return output

def InceptionNet(input_shape, num_classes):
    inputs = tf.keras.Input(shape=input_shape)

    x = Conv2D(64, (7, 7), strides=(2, 2), padding='same', activation='relu')(inputs)
    x = MaxPooling2D(pool_size=(3, 3), strides=(2, 2), padding='same')(x)
    x = BatchNormalization()(x)

    x = Conv2D(64, (1, 1), strides=(1, 1), padding='same', activation='relu')(x)
    x = Conv2D(192, (3, 3), strides=(1, 1), padding='same', activation='relu')(x)
    x = BatchNormalization()(x)
    x = MaxPooling2D(pool_size=(3, 3), strides=(2, 2), padding='same')(x)

    x = inception_module(x, filters=[64, 96, 128, 16])
    x = inception_module(x, filters=[128, 128, 192, 32])
    x = MaxPooling2D(pool_size=(3, 3), strides=(2, 2), padding='same')(x)

    x = inception_module(x, filters=[192, 96, 208, 16])
    x = inception_module(x, filters=[160, 112, 224, 24])
    x = inception_module(x, filters=[128, 128, 256, 24])
    x = inception_module(x, filters=[112, 144, 288, 32])
    x = inception_module(x, filters=[256, 160, 320, 32])
    x = MaxPooling2D(pool_size=(3, 3), strides=(2, 2), padding='same')(x)

    x = inception_module(x, filters=[256, 160, 320, 32])
    x = inception_module(x, filters=[384, 192, 384, 48])

    x = AveragePooling2D(pool_size=(7, 7), strides=(1, 1), padding='valid')(x)
    x = Dropout(0.4)(x)
    x = Flatten()(x)
    x = Dense(1000, activation='relu')(x)
    x = Dropout(0.4)(x)
    x = Dense(num_classes, activation='softmax')(x)

    model = Model(inputs=inputs, outputs=x)
    return model

# Define the input shape and number of classes
input_shape = (224, 224, 3)
num_classes = 1000

# Create the InceptionNet model
model = InceptionNet(input_shape, num_classes)

# Print the model summary
model.summary()

In [ ]:
model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])

In [ ]:
%%time
model.fit(x_train, y_train, epochs=100)

Epoch 1/100
36/36 [==============================] - 36s 31ms/step - loss: 2.3939 - accuracy: 0.1155
Epoch 2/100
36/36 [==============================] - 1s 31ms/step - loss: 2.1258 - accuracy: 0.1128
Epoch 3/100
36/36 [==============================] - 1s 30ms/step - loss: 2.0996 - accuracy: 0.1128
Epoch 4/100
36/36 [==============================] - 1s 31ms/step - loss: 2.0905 - accuracy: 0.1181
Epoch 5/100
36/36 [==============================] - 1s 31ms/step - loss: 2.0796 - accuracy: 0.1276
Epoch 6/100
36/36 [==============================] - 1s 31ms/step - loss: 2.0833 - accuracy: 0.1345
Epoch 7/100
36/36 [==============================] - 1s 31ms/step - loss: 2.0859 - accuracy: 0.1267
Epoch 8/100
36/36 [==============================] - 1s 31ms/step - loss: 2.0749 - accuracy: 0.1510
Epoch 9/100
36/36 [==============================] - 1s 31ms/step - loss: 2.0795 - accuracy: 0.1319
Epoch 10/100
36/36 [==============================] - 1s 31ms/step - loss: 2.0771 - accuracy: 0.142

In [ ]:
predictions = model.predict(x_test)
predicted_classes = np.argmax(predictions, axis=1)

9/9 [==============================] - 1s 11ms/step


In [ ]:
predictions
y_test
new_Ytest = y_test.astype(int)
new_Ytest

array([1, 1, 0, 1, 0, 4, 3, 1, 1, 6, 7, 4, 2, 3, 3, 5, 2, 3, 7, 4, 3, 7,
       0, 1, 4, 7, 7, 5, 3, 2, 0, 4, 4, 2, 1, 0, 1, 3, 1, 1, 0, 5, 2, 3,
       2, 0, 0, 3, 6, 2, 3, 5, 1, 7, 1, 2, 6, 4, 2, 0, 1, 6, 2, 2, 4, 7,
       7, 4, 6, 4, 7, 0, 6, 6, 7, 3, 0, 6, 0, 1, 3, 3, 7, 7, 3, 3, 4, 4,
       7, 2, 0, 0, 0, 2, 6, 5, 3, 2, 4, 7, 0, 1, 1, 1, 6, 4, 0, 4, 7, 0,
       4, 0, 4, 0, 1, 6, 4, 1, 0, 6, 1, 1, 7, 1, 3, 7, 2, 2, 6, 6, 1, 2,
       2, 2, 2, 5, 4, 0, 1, 6, 0, 7, 1, 1, 5, 5, 3, 7, 6, 6, 2, 2, 6, 4,
       6, 5, 7, 2, 3, 1, 3, 1, 6, 5, 3, 1, 0, 4, 7, 5, 0, 6, 4, 2, 2, 2,
       4, 2, 6, 1, 1, 6, 4, 7, 7, 2, 1, 6, 7, 2, 7, 0, 2, 1, 5, 3, 4, 5,
       4, 7, 3, 6, 0, 2, 7, 0, 7, 3, 1, 4, 0, 6, 2, 4, 4, 1, 4, 3, 3, 5,
       1, 3, 7, 3, 3, 2, 3, 3, 2, 5, 1, 5, 1, 3, 0, 2, 6, 0, 3, 4, 3, 3,
       1, 4, 1, 7, 2, 0, 7, 0, 0, 3, 0, 7, 2, 4, 0, 0, 6, 5, 3, 5, 6, 2,
       6, 6, 0, 7, 3, 7, 0, 7, 5, 6, 3, 3, 7, 6, 7, 4, 6, 4, 1, 0, 1, 0,
       1, 6])

In [ ]:
from sklearn.metrics import classification_report

report = classification_report(new_Ytest, predicted_classes)
print(report)


              precision    recall  f1-score   support

           0       0.00      0.00      0.00        41
           1       0.00      0.00      0.00        43
           2       0.14      1.00      0.25        38
           3       0.00      0.00      0.00        40
           4       0.00      0.00      0.00        35
           5       0.00      0.00      0.00        19
           6       0.00      0.00      0.00        35
           7       0.18      0.08      0.11        37

    accuracy                           0.14       288
   macro avg       0.04      0.14      0.04       288
weighted avg       0.04      0.14      0.05       288



In [ ]:
from sklearn.metrics import confusion_matrix

new_Ytest = new_Ytest.astype(int)
matrix = confusion_matrix(new_Ytest, predicted_classes)
print(matrix)

[[ 0  0 40  0  0  0  0  1]
 [ 0  0 43  0  0  0  0  0]
 [ 0  0 38  0  0  0  0  0]
 [ 0  0 39  0  0  0  0  1]
 [ 0  0 27  0  0  0  0  8]
 [ 0  0 16  0  0  0  0  3]
 [ 0  0 34  0  0  0  0  1]
 [ 0  0 34  0  0  0  0  3]]


In [ ]:
# pred = model.predict(x_test)
# plt.figure(1 , figsize = (19 , 10))
# n = 0

# for i in range(9):
#     n += 1
#     r = np.random.randint( 0, x_test.shape[0], 1)

#     plt.subplot(3, 3, n)
#     plt.subplots_adjust(hspace = 0.3, wspace = 0.3)

#     plt.imshow(x_test[r[0]])
#     plt.title('Actual = {}, Predicted = {}'.format(y_test[r[0]] , y_test[r[0]]*pred[r[0]][y_test[r[0]]]) )
#     plt.xticks([]) , plt.yticks([])

# plt.show()

In [ ]:
# from keras.layers import Dense, Flatten, Reshape, Input, InputLayer
# from keras.models import Sequential, Model

# def build_autoencoder(img_shape, code_size):
#     # The encoder
#     encoder = Sequential()
#     encoder.add(InputLayer(img_shape))
#     encoder.add(Flatten())
#     encoder.add(Dense(code_size))

#     # The decoder
#     decoder = Sequential()
#     decoder.add(InputLayer((code_size,)))
#     decoder.add(Dense(np.prod(img_shape))) # np.prod(img_shape) is the same as 32*32*3, it's more generic than saying 3072
#     decoder.add(Reshape(img_shape))

#     return encoder, decoder

In [ ]:
# IMG_SHAPE = images.shape[1:]
# encoder, decoder = build_autoencoder(IMG_SHAPE, 32)

# inp = Input(IMG_SHAPE)
# code = encoder(inp)
# reconstruction = decoder(code)

# autoencoder = Model(inp,reconstruction)
# autoencoder.compile(optimizer='adamax', loss='mse')

# print(autoencoder.summary())

In [ ]:
# history = autoencoder.fit(x=x_train, y=x_train, epochs=20,
#                 validation_data=[x_test, x_test])

In [ ]:
# decoded_imgs = autoencoder.predict(images)

# n = 1
# plt.figure(figsize=(20, 4))
# for i in range(n):
#     # display original
#     ax = plt.subplot(2, n, i+1)
#     plt.imshow(x_test[i].reshape(224, 224,3))
#     plt.gray()
#     ax.get_xaxis().set_visible(False)
#     ax.get_yaxis().set_visible(False)

#     # display reconstruction
#     ax = plt.subplot(2, n, i + n+1)
#     plt.imshow(decoded_imgs[i].reshape(224, 224,3))
#     plt.gray()
#     ax.get_xaxis().set_visible(False)
#     ax.get_yaxis().set_visible(False)
# plt.show()

# print("Accuracy=",1-np.mean(abs(images-decoded_imgs)),'\n')

In [ ]:
# decoded_imgs = autoencoder.predict(images)
# n = 1
# plt.figure(figsize=(20, 4))
# for i in range(n):
#     # display original
#     ax = plt.subplot(2, n, i+1)
#     plt.imshow(images[i].reshape(224, 224,3))
#     plt.gray()
#     ax.get_xaxis().set_visible(False)
#     ax.get_yaxis().set_visible(False)

#     # display reconstruction
#     ax = plt.subplot(2, n, i + n+1)
#     plt.imshow(decoded_imgs[i].reshape(224, 224,3))
#     plt.gray()
#     ax.get_xaxis().set_visible(False)
#     ax.get_yaxis().set_visible(False)
# plt.show()

# print("Accuracy=",1-np.mean(abs(images-decoded_imgs)),'\n')

In [ ]:
# X_train, X_test, Y_train, Y_test = train_test_split(decoded_imgs, labels, test_size = 0.2, random_state = random_seed)

# print("x_train shape = ",X_train.shape)
# print("y_train shape = ",Y_train.shape)
# print("\nx_test shape = ",X_test.shape)
# print("y_test shape = ",Y_test.shape)

In [ ]:
# %%time
# model.fit(X_train, Y_train, epochs=500, batch_size=32)

In [ ]:
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Test loss: 2.061994791030884
Test accuracy: 0.1215277761220932


In [ ]:
predictions_new = np.argmax(model.predict(x_test), axis=-1)
predictions_new
y_test
new_Ytest_new = y_test.astype(int)
new_Ytest_new

9/9 [==============================] - 0s 11ms/step


array([1, 1, 0, 1, 0, 4, 3, 1, 1, 6, 7, 4, 2, 3, 3, 5, 2, 3, 7, 4, 3, 7,
       0, 1, 4, 7, 7, 5, 3, 2, 0, 4, 4, 2, 1, 0, 1, 3, 1, 1, 0, 5, 2, 3,
       2, 0, 0, 3, 6, 2, 3, 5, 1, 7, 1, 2, 6, 4, 2, 0, 1, 6, 2, 2, 4, 7,
       7, 4, 6, 4, 7, 0, 6, 6, 7, 3, 0, 6, 0, 1, 3, 3, 7, 7, 3, 3, 4, 4,
       7, 2, 0, 0, 0, 2, 6, 5, 3, 2, 4, 7, 0, 1, 1, 1, 6, 4, 0, 4, 7, 0,
       4, 0, 4, 0, 1, 6, 4, 1, 0, 6, 1, 1, 7, 1, 3, 7, 2, 2, 6, 6, 1, 2,
       2, 2, 2, 5, 4, 0, 1, 6, 0, 7, 1, 1, 5, 5, 3, 7, 6, 6, 2, 2, 6, 4,
       6, 5, 7, 2, 3, 1, 3, 1, 6, 5, 3, 1, 0, 4, 7, 5, 0, 6, 4, 2, 2, 2,
       4, 2, 6, 1, 1, 6, 4, 7, 7, 2, 1, 6, 7, 2, 7, 0, 2, 1, 5, 3, 4, 5,
       4, 7, 3, 6, 0, 2, 7, 0, 7, 3, 1, 4, 0, 6, 2, 4, 4, 1, 4, 3, 3, 5,
       1, 3, 7, 3, 3, 2, 3, 3, 2, 5, 1, 5, 1, 3, 0, 2, 6, 0, 3, 4, 3, 3,
       1, 4, 1, 7, 2, 0, 7, 0, 0, 3, 0, 7, 2, 4, 0, 0, 6, 5, 3, 5, 6, 2,
       6, 6, 0, 7, 3, 7, 0, 7, 5, 6, 3, 3, 7, 6, 7, 4, 6, 4, 1, 0, 1, 0,
       1, 6])

In [ ]:
from sklearn.metrics import classification_report
report = classification_report(new_Ytest_new, predictions_new)
print(report)

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        41
           1       0.00      0.00      0.00        43
           2       0.00      0.00      0.00        38
           3       0.00      0.00      0.00        40
           4       0.12      1.00      0.22        35
           5       0.00      0.00      0.00        19
           6       0.00      0.00      0.00        35
           7       0.00      0.00      0.00        37

    accuracy                           0.12       288
   macro avg       0.02      0.12      0.03       288
weighted avg       0.01      0.12      0.03       288



In [ ]:
from sklearn.metrics import classification_report, matthews_corrcoef

report = classification_report(new_Ytest_new, predictions_new)
print(report)

# Calculate MCC for each emotion
emotions = [0, 1, 2, 3, 4, 5, 6, 7]  # Replace with your actual emotion labels
mcc_scores = {}
for emotion in emotions:
    emotion_indices = (new_Ytest_new == emotion)
    emotion_predictions = predictions_new[emotion_indices]
    emotion_labels = new_Ytest_new[emotion_indices]
    mcc_scores[emotion] = matthews_corrcoef(emotion_labels, emotion_predictions)

# Print MCC scores for each emotion
for emotion, mcc in mcc_scores.items():
    print(f"MCC for emotion {emotion}: {mcc}")



              precision    recall  f1-score   support

           0       0.00      0.00      0.00        41
           1       0.00      0.00      0.00        43
           2       0.00      0.00      0.00        38
           3       0.00      0.00      0.00        40
           4       0.12      1.00      0.22        35
           5       0.00      0.00      0.00        19
           6       0.00      0.00      0.00        35
           7       0.00      0.00      0.00        37

    accuracy                           0.12       288
   macro avg       0.02      0.12      0.03       288
weighted avg       0.01      0.12      0.03       288

MCC for emotion 0: 0.0
MCC for emotion 1: 0.0
MCC for emotion 2: 0.0
MCC for emotion 3: 0.0
MCC for emotion 4: 0.0
MCC for emotion 5: 0.0
MCC for emotion 6: 0.0
MCC for emotion 7: 0.0


In [ ]:
import matplotlib.pyplot as plt

# Train the model and obtain the history object
history = model.fit(x_train, y_train, epochs=50, validation_data=(x_test, y_test))

# Plot the accuracy curve
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend(['Train', 'Validation'], loc='upper left')
plt.show()

# Plot the loss curve
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Model Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend(['Train', 'Validation'], loc='upper right')
plt.show()